name: kitchensync

options:
  bundleIdPrefix: com.supergamer474

configs:
  Release: release

targets:
  kitchensync:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [Sources/kitchensync]
    bundleId: com.supergamer474.kitchensync
    settings:
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
    info:
      path: "Info.plist"
      properties:
        CFBundleDisplayName: "KS Counter"
        CFBundleName: "kitchensync"
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.2"
        UILaunchStoryboardName: "LaunchScreen"
        NSPrincipalClass: "UIApplication"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true
        CFBundleURLTypes:
          - CFBundleURLName: "com.supergamer474.kitchensync"
            CFBundleURLSchemes:
              - kitchensync
              - KitchenSync
